package com.example.origy.ui.product

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.viewModelScope
import com.example.origy.R
import com.example.origy.base.viewModel.BaseViewModel
import com.example.origy.database.AppDatabase
import kotlinx.coroutines.launch


class ProductViewModel (application: Application) : BaseViewModel(application){
    private val dao = AppDatabase.get(application).ProductDao()
    private val itemDao = AppDatabase.get(application).ItemDetailDao()
    val favorite = MutableLiveData<Boolean>()

    fun loadProduct() {
        launch {
            val newData = getProduct()
            val oldData = dao.getAll()

            if (oldData != newData) {
                dao.deleteAll()
                newData.forEach {
                    dao.insert(it)
                }
            }
        }
    }

    private fun getProduct(): List<ProductEntity>{
        return listOf(
            ProductEntity(productId = 1, image = R.drawable.ninja_start_1, stepNumber = 1, id = 101),
            ProductEntity(productId = 1, image = R.drawable.ninja_start_2, stepNumber = 2, id = 102),
            ProductEntity(productId = 1, image = R.drawable.ninja_start_3, stepNumber = 3, id = 103),
            ProductEntity(productId = 1, image = R.drawable.ninja_stra_4, stepNumber = 4, id = 104),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_5, stepNumber = 5, id = 105),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_6, stepNumber = 6, id = 106),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_7, stepNumber = 7, id = 107),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_8, stepNumber = 8, id = 108),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_9, stepNumber = 9, id = 109),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_10, stepNumber = 10, id = 110),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_11, stepNumber = 11, id = 111),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_12, stepNumber = 12, id = 112),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_13, stepNumber = 13, id = 113),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_14, stepNumber = 14, id = 114),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_15, stepNumber = 15, id = 115),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_16, stepNumber = 16, id = 116),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_17, stepNumber = 17, id = 117),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_18, stepNumber = 18, id = 118),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_19, stepNumber = 19, id = 119),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_20, stepNumber = 20, id = 120),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_21, stepNumber = 21, id = 121),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_22, stepNumber = 22, id = 122),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_23, stepNumber = 23, id = 123),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_24, stepNumber = 24, id = 124),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_25, stepNumber = 25, id = 125),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_26, stepNumber = 26, id = 126),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_27, stepNumber = 27, id = 127),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_28, stepNumber = 28, id = 128),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_29, stepNumber = 29, id = 129),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_30, stepNumber = 30, id = 130),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_31, stepNumber = 31, id = 131),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_32, stepNumber = 32, id = 132),
            ProductEntity(productId = 1, image = R.drawable.ninja_star_33, stepNumber = 33, id = 133),


            ProductEntity(productId = 2, image = R.drawable.kunai_1, stepNumber = 1, id = 201),
            ProductEntity(productId = 2, image = R.drawable.kunai_2, stepNumber = 2, id = 202),
            ProductEntity(productId = 2, image = R.drawable.kunai_3, stepNumber = 3, id = 203),
            ProductEntity(productId = 2, image = R.drawable.kunai_4, stepNumber = 4, id = 204),
            ProductEntity(productId = 2, image = R.drawable.kunai_5, stepNumber = 5, id = 205),
            ProductEntity(productId = 2, image = R.drawable.kunai_6, stepNumber = 6, id = 206),
            ProductEntity(productId = 2, image = R.drawable.kunai_7, stepNumber = 7, id = 207),
            ProductEntity(productId = 2, image = R.drawable.kunai_8, stepNumber = 8, id = 208),
            ProductEntity(productId = 2, image = R.drawable.kunai_9, stepNumber = 9, id = 209),
            ProductEntity(productId = 2, image = R.drawable.kunai_10, stepNumber = 10, id = 210),
            ProductEntity(productId = 2, image = R.drawable.kunai_11, stepNumber = 11, id = 211),
            ProductEntity(productId = 2, image = R.drawable.kunai_12, stepNumber = 12, id = 212),
            ProductEntity(productId = 2, image = R.drawable.kunai_13, stepNumber = 13, id = 213),
            ProductEntity(productId = 2, image = R.drawable.kunai_14, stepNumber = 14, id = 214),
            ProductEntity(productId = 2, image = R.drawable.kunai_15, stepNumber = 15, id = 215),
            ProductEntity(productId = 2, image = R.drawable.kunai_16, stepNumber = 16, id = 216),
            ProductEntity(productId = 2, image = R.drawable.kunai_17, stepNumber = 19, id = 217),
            ProductEntity(productId = 2, image = R.drawable.kunai_18, stepNumber = 18, id = 218),
            ProductEntity(productId = 2, image = R.drawable.kunai_19, stepNumber = 19, id = 219),



            ProductEntity(productId = 3, image = R.drawable.airplane_1, stepNumber = 1, id = 301),
            ProductEntity(productId = 3, image = R.drawable.airplane_2, stepNumber = 2, id = 302),
            ProductEntity(productId = 3, image = R.drawable.airplane_3, stepNumber = 3, id = 303),
            ProductEntity(productId = 3, image = R.drawable.airplane_4, stepNumber = 4, id = 304),
            ProductEntity(productId = 3, image = R.drawable.airplane_5, stepNumber = 5, id = 305),
            ProductEntity(productId = 3, image = R.drawable.airplane_6, stepNumber = 6, id = 306),
            ProductEntity(productId = 3, image = R.drawable.airplane_7, stepNumber = 7, id = 307),
            ProductEntity(productId = 3, image = R.drawable.airplane_8, stepNumber = 8, id = 308),
            ProductEntity(productId = 3, image = R.drawable.airplane_9, stepNumber = 9, id = 309),
            ProductEntity(productId = 3, image = R.drawable.airplane_10, stepNumber = 10, id = 310),
            ProductEntity(productId = 3, image = R.drawable.airplane_11, stepNumber = 11, id = 311),
            ProductEntity(productId = 3, image = R.drawable.airplane_12, stepNumber = 12, id = 312),
            ProductEntity(productId = 3, image = R.drawable.airplane_13, stepNumber = 13, id = 313),
            ProductEntity(productId = 3, image = R.drawable.airplane_14, stepNumber = 14, id = 314),
            ProductEntity(productId = 3, image = R.drawable.airplane_15, stepNumber = 15, id = 315),
            ProductEntity(productId = 3, image = R.drawable.airplane_16, stepNumber = 16, id = 316),
            ProductEntity(productId = 3, image = R.drawable.airplane_17, stepNumber = 17, id = 317),
            ProductEntity(productId = 3, image = R.drawable.airplane_18, stepNumber = 18, id = 318),
            ProductEntity(productId = 3, image = R.drawable.airplane_19, stepNumber = 19, id = 319),
            ProductEntity(productId = 3, image = R.drawable.airplane_20, stepNumber = 20, id = 320),
            ProductEntity(productId = 3, image = R.drawable.airplane_21, stepNumber = 21, id = 321),
            ProductEntity(productId = 3, image = R.drawable.airplane_22, stepNumber = 22, id = 322),
            ProductEntity(productId = 3, image = R.drawable.airplane_23, stepNumber = 23, id = 323),
            ProductEntity(productId = 3, image = R.drawable.airplane_24, stepNumber = 24, id = 324),
            ProductEntity(productId = 3, image = R.drawable.airplane_25, stepNumber = 25, id = 325),
            ProductEntity(productId = 3, image = R.drawable.airplane_26, stepNumber = 26, id = 326),
            ProductEntity(productId = 3, image = R.drawable.airplane_27, stepNumber = 27, id = 327),

            ProductEntity(productId = 4, image = R.drawable.boat_1, stepNumber = 1, id = 401),
            ProductEntity(productId = 4, image = R.drawable.boat_2, stepNumber = 2, id = 402),
            ProductEntity(productId = 4, image = R.drawable.boat_3, stepNumber = 3, id = 403),
            ProductEntity(productId = 4, image = R.drawable.boat_4, stepNumber = 4, id = 404),
            ProductEntity(productId = 4, image = R.drawable.boat_5, stepNumber = 5, id = 405),
            ProductEntity(productId = 4, image = R.drawable.boat_6, stepNumber = 6, id = 406),
            ProductEntity(productId = 4, image = R.drawable.boat_7, stepNumber = 7, id = 407),
            ProductEntity(productId = 4, image = R.drawable.boat_8, stepNumber = 8, id = 408),
            ProductEntity(productId = 4, image = R.drawable.boat_9, stepNumber = 9, id = 409),
            ProductEntity(productId = 4, image = R.drawable.boat_10, stepNumber = 10, id = 410),
            ProductEntity(productId = 4, image = R.drawable.boat_11, stepNumber = 11, id = 411),
            ProductEntity(productId = 4, image = R.drawable.boat_12, stepNumber = 12, id = 412),
            ProductEntity(productId = 4, image = R.drawable.boat_13, stepNumber = 13, id = 413),
            ProductEntity(productId = 4, image = R.drawable.boat_14, stepNumber = 14, id = 414),
            ProductEntity(productId = 4, image = R.drawable.boat_15, stepNumber = 15, id = 415),
            ProductEntity(productId = 4, image = R.drawable.boat_16, stepNumber = 16, id = 416),
            ProductEntity(productId = 4, image = R.drawable.boat_17, stepNumber = 17, id = 417),
            ProductEntity(productId = 4, image = R.drawable.boat_18, stepNumber = 18, id = 418),
            ProductEntity(productId = 4, image = R.drawable.boat_19, stepNumber = 19, id = 419),
            ProductEntity(productId = 4, image = R.drawable.boat_20, stepNumber = 20, id = 420),
            ProductEntity(productId = 4, image = R.drawable.boat_21, stepNumber = 21, id = 421),
            ProductEntity(productId = 4, image = R.drawable.boat_22, stepNumber = 22, id = 422),

            ProductEntity(productId = 5, image = R.drawable.car_1, stepNumber = 1, id = 501),
            ProductEntity(productId = 5, image = R.drawable.car_2, stepNumber = 2, id = 502),
            ProductEntity(productId = 5, image = R.drawable.car_3, stepNumber = 3, id = 503),
            ProductEntity(productId = 5, image = R.drawable.car_4, stepNumber = 4, id = 504),
            ProductEntity(productId = 5, image = R.drawable.car_5, stepNumber = 5, id = 505),
            ProductEntity(productId = 5, image = R.drawable.car_6, stepNumber = 6, id = 506),
            ProductEntity(productId = 5, image = R.drawable.car_7, stepNumber = 7, id = 507),
            ProductEntity(productId = 5, image = R.drawable.car_8, stepNumber = 8, id = 508),
            ProductEntity(productId = 5, image = R.drawable.car_9, stepNumber = 9, id = 509),
            ProductEntity(productId = 5, image = R.drawable.car_10, stepNumber = 10, id = 510),
            ProductEntity(productId = 5, image = R.drawable.car_11, stepNumber = 11, id = 511),
            ProductEntity(productId = 5, image = R.drawable.car_12, stepNumber = 12, id = 512),
            ProductEntity(productId = 5, image = R.drawable.car_13, stepNumber = 13, id = 513),
            ProductEntity(productId = 5, image = R.drawable.car_14, stepNumber = 14, id = 514),
            ProductEntity(productId = 5, image = R.drawable.car_15, stepNumber = 15, id = 515),
            ProductEntity(productId = 5, image = R.drawable.car_16, stepNumber = 16, id = 516),
            ProductEntity(productId = 5, image = R.drawable.car_17, stepNumber = 17, id = 517),
            ProductEntity(productId = 5, image = R.drawable.car_18, stepNumber = 18, id = 518),
            ProductEntity(productId = 5, image = R.drawable.car_19, stepNumber = 19, id = 519),
            ProductEntity(productId = 5, image = R.drawable.car_20, stepNumber = 20, id = 520),
            ProductEntity(productId = 5, image = R.drawable.car_21, stepNumber = 21, id = 521),
            ProductEntity(productId = 5, image = R.drawable.car_22, stepNumber = 22, id = 522),
            ProductEntity(productId = 5, image = R.drawable.car_23, stepNumber = 23, id = 523),
            ProductEntity(productId = 5, image = R.drawable.car_24, stepNumber = 24, id = 524),
            ProductEntity(productId = 5, image = R.drawable.car_25, stepNumber = 25, id = 525),
            ProductEntity(productId = 5, image = R.drawable.car_26, stepNumber = 26, id = 526),
            ProductEntity(productId = 5, image = R.drawable.car_27, stepNumber = 27, id = 527),
            ProductEntity(productId = 5, image = R.drawable.car_28, stepNumber = 28, id =528),
            ProductEntity(productId = 5, image = R.drawable.car_29, stepNumber = 29, id = 529),
            ProductEntity(productId = 5, image = R.drawable.car_30, stepNumber = 30, id = 530),

            ProductEntity(productId = 6, image = R.drawable.robot_1, stepNumber = 1, id = 601),
            ProductEntity(productId = 6, image = R.drawable.robot_2, stepNumber = 2, id = 602),
            ProductEntity(productId = 6, image = R.drawable.robot_3, stepNumber = 3, id = 603),
            ProductEntity(productId = 6, image = R.drawable.robot_4, stepNumber = 4, id = 604),
            ProductEntity(productId = 6, image = R.drawable.robot_5, stepNumber = 5, id = 605),
            ProductEntity(productId = 6, image = R.drawable.robot_6, stepNumber = 6, id = 606),
            ProductEntity(productId = 6, image = R.drawable.robot_7, stepNumber = 7, id = 607),
            ProductEntity(productId = 6, image = R.drawable.robot_8, stepNumber = 8, id = 608),
            ProductEntity(productId = 6, image = R.drawable.robot_9, stepNumber = 9, id = 609),
            ProductEntity(productId = 6, image = R.drawable.robot_10, stepNumber = 10, id = 610),
            ProductEntity(productId = 6, image = R.drawable.robot_11, stepNumber = 11, id = 611),
            ProductEntity(productId = 6, image = R.drawable.robot_12, stepNumber = 12, id = 612),
            ProductEntity(productId = 6, image = R.drawable.robot_13, stepNumber = 13, id = 613),
            ProductEntity(productId = 6, image = R.drawable.robot_14, stepNumber = 14, id = 614),
            ProductEntity(productId = 6, image = R.drawable.robot_15, stepNumber = 15, id = 615),
            ProductEntity(productId = 6, image = R.drawable.robot_16, stepNumber = 16, id = 616),
            ProductEntity(productId = 6, image = R.drawable.robot_17, stepNumber = 17, id = 617),
            ProductEntity(productId = 6, image = R.drawable.robot_18, stepNumber = 18, id = 618),
            ProductEntity(productId = 6, image = R.drawable.robot_19, stepNumber = 19, id = 619),
            ProductEntity(productId = 6, image = R.drawable.robot_20, stepNumber = 20, id = 620),
            ProductEntity(productId = 6, image = R.drawable.robot_21, stepNumber = 21, id = 621),
            ProductEntity(productId = 6, image = R.drawable.robot_22, stepNumber = 22, id = 622),
            ProductEntity(productId = 6, image = R.drawable.robot_23, stepNumber = 23, id = 623),
            ProductEntity(productId = 6, image = R.drawable.robot_24, stepNumber = 24, id = 624),
            ProductEntity(productId = 6, image = R.drawable.robot_25, stepNumber = 25, id = 625),
            ProductEntity(productId = 6, image = R.drawable.robot_26, stepNumber = 26, id = 626),
            ProductEntity(productId = 6, image = R.drawable.robot_27, stepNumber = 27, id = 627),
            ProductEntity(productId = 6, image = R.drawable.robot_28, stepNumber = 28, id = 628),
            ProductEntity(productId = 6, image = R.drawable.robot_29, stepNumber = 29, id = 629),
            ProductEntity(productId = 6, image = R.drawable.robot_30, stepNumber = 30, id = 630),
            ProductEntity(productId = 6, image = R.drawable.robot_40, stepNumber = 40, id = 640),
            ProductEntity(productId = 6, image = R.drawable.robot_41, stepNumber = 41, id = 641),
            ProductEntity(productId = 6, image = R.drawable.robot_42, stepNumber = 42, id = 642),
            ProductEntity(productId = 6, image = R.drawable.robot_43, stepNumber = 43, id = 643),
            ProductEntity(productId = 6, image = R.drawable.robot_44, stepNumber = 44, id = 644),
            ProductEntity(productId = 6, image = R.drawable.robot_45, stepNumber = 45, id = 645),
            ProductEntity(productId = 6, image = R.drawable.robot_46, stepNumber = 46, id = 646),
            ProductEntity(productId = 6, image = R.drawable.robot_47, stepNumber = 47, id = 647),
            ProductEntity(productId = 6, image = R.drawable.robot_48, stepNumber = 48, id = 648),
            ProductEntity(productId = 6, image = R.drawable.robot_49, stepNumber = 49, id = 649),
            ProductEntity(productId = 6, image = R.drawable.robot_50, stepNumber = 50, id = 650),
            ProductEntity(productId = 6, image = R.drawable.robot_51, stepNumber = 51, id = 651),
            ProductEntity(productId = 6, image = R.drawable.robot_52, stepNumber = 52, id = 652),


            ProductEntity(productId = 7, image = R.drawable.frog_1, stepNumber = 1, id = 701),
            ProductEntity(productId = 7, image = R.drawable.frog_2, stepNumber = 2, id = 702),
            ProductEntity(productId = 7, image = R.drawable.frog_3, stepNumber = 3, id = 703),
            ProductEntity(productId = 7, image = R.drawable.frog_4, stepNumber = 4, id = 704),
            ProductEntity(productId = 7, image = R.drawable.frog_5, stepNumber = 5, id = 705),
            ProductEntity(productId = 7, image = R.drawable.frog_6, stepNumber = 6, id = 706),
            ProductEntity(productId = 7, image = R.drawable.frog_7, stepNumber = 7, id = 707),
            ProductEntity(productId = 7, image = R.drawable.frog_8, stepNumber = 8, id = 708),
            ProductEntity(productId = 7, image = R.drawable.frog_9, stepNumber = 9, id = 709),

            ProductEntity(productId = 8, image = R.drawable.bird_1, stepNumber = 1, id = 801),
            ProductEntity(productId = 8, image = R.drawable.bird_2, stepNumber = 2, id = 802),
            ProductEntity(productId = 8, image = R.drawable.bird_3, stepNumber = 3, id = 803),
            ProductEntity(productId = 8, image = R.drawable.bird_4, stepNumber = 4, id = 804),
            ProductEntity(productId = 8, image = R.drawable.bird_5, stepNumber = 5, id = 805),
            ProductEntity(productId = 8, image = R.drawable.bird_6, stepNumber = 6, id = 806),
            ProductEntity(productId = 8, image = R.drawable.bird_7, stepNumber = 7, id = 807),
            ProductEntity(productId = 8, image = R.drawable.bird_8, stepNumber = 8, id = 808),
            ProductEntity(productId = 8, image = R.drawable.bird_9, stepNumber = 9, id = 809),
            ProductEntity(productId = 8, image = R.drawable.bird_10, stepNumber = 10, id = 810),
            ProductEntity(productId = 8, image = R.drawable.bird_11, stepNumber = 11, id = 811),

            ProductEntity(productId = 9, image = R.drawable.dinosaurs_1, stepNumber = 1, id = 901),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_2, stepNumber = 2, id = 902),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_3, stepNumber = 3, id = 903),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_4, stepNumber = 4, id = 904),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_5, stepNumber = 5, id = 905),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_6, stepNumber = 6, id = 906),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_7, stepNumber = 7, id = 907),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_8, stepNumber = 8, id = 908),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_9, stepNumber = 9, id = 909),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_10, stepNumber = 10, id = 910),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_11, stepNumber = 11, id = 911),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_12, stepNumber = 12, id = 912),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_13, stepNumber = 13, id = 913),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_14, stepNumber = 14, id = 914),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_15, stepNumber = 15, id = 915),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_16, stepNumber = 16, id = 916),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_17, stepNumber = 17, id = 917),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_18, stepNumber = 18, id = 918),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_19, stepNumber = 19, id = 919),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_20, stepNumber = 20, id = 920),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_21, stepNumber = 21, id = 921),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_22, stepNumber = 22, id = 922),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_23, stepNumber = 23, id = 923),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_24, stepNumber = 24, id = 924),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_25, stepNumber = 25, id = 925),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_26, stepNumber = 26, id = 926),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_27, stepNumber = 27, id = 927),
            ProductEntity(productId = 9, image = R.drawable.dinosaurs_28, stepNumber = 28, id = 928),


            ProductEntity(productId = 10, image = R.drawable.dragon_1, stepNumber = 1, id = 1001),
            ProductEntity(productId = 10, image = R.drawable.dragon_2, stepNumber = 2, id = 1002),
            ProductEntity(productId = 10, image = R.drawable.dragon_3, stepNumber = 3, id = 1003),
            ProductEntity(productId = 10, image = R.drawable.dragon_4, stepNumber = 4, id = 1004),
            ProductEntity(productId = 10, image = R.drawable.dragon_5, stepNumber = 5, id = 1005),
            ProductEntity(productId = 10, image = R.drawable.dragon_6, stepNumber = 6, id = 1006),
            ProductEntity(productId = 10, image = R.drawable.dragon_7, stepNumber = 7, id = 1007),
            ProductEntity(productId = 10, image = R.drawable.dragon_8, stepNumber = 8, id = 1008),
            ProductEntity(productId = 10, image = R.drawable.dragon_9, stepNumber = 9, id = 1009),
            ProductEntity(productId = 10, image = R.drawable.dragon_10, stepNumber = 10, id = 1010),
            ProductEntity(productId = 10, image = R.drawable.dragon_11, stepNumber = 11, id = 1011),
            ProductEntity(productId = 10, image = R.drawable.dragon_12, stepNumber = 12, id = 1012),
            ProductEntity(productId = 10, image = R.drawable.dragon_13, stepNumber = 13, id = 1013),
            ProductEntity(productId = 10, image = R.drawable.dragon_14, stepNumber = 14, id = 1014),
            ProductEntity(productId = 10, image = R.drawable.dragon_15, stepNumber = 15, id = 1015),
            ProductEntity(productId = 10, image = R.drawable.dragon_16, stepNumber = 16, id = 1016),
            ProductEntity(productId = 10, image = R.drawable.dragon_17, stepNumber = 17, id = 1017),
            ProductEntity(productId = 10, image = R.drawable.dragon_18, stepNumber = 18, id = 1018),
            ProductEntity(productId = 10, image = R.drawable.dragon_19, stepNumber = 19, id = 1019),
            ProductEntity(productId = 10, image = R.drawable.dragon_20, stepNumber = 20, id = 1020),
            ProductEntity(productId = 10, image = R.drawable.dragon_21, stepNumber = 21, id = 1021),
            ProductEntity(productId = 10, image = R.drawable.dragon_22, stepNumber = 22, id = 1022),
            ProductEntity(productId = 10, image = R.drawable.dragon_23, stepNumber = 23, id = 1023),
            ProductEntity(productId = 10, image = R.drawable.dragon_24, stepNumber = 24, id = 1024),
            ProductEntity(productId = 10, image = R.drawable.dragon_25, stepNumber = 25, id = 1025),
            ProductEntity(productId = 10, image = R.drawable.dragon_26, stepNumber = 26, id = 1026),
            ProductEntity(productId = 10, image = R.drawable.dragon_27, stepNumber = 27, id = 1027),
            ProductEntity(productId = 10, image = R.drawable.dragon_28, stepNumber = 28, id = 1028),
            ProductEntity(productId = 10, image = R.drawable.dragon_29, stepNumber = 29, id = 1029),
            ProductEntity(productId = 10, image = R.drawable.dragon_30, stepNumber = 30, id = 1030),


            ProductEntity(productId = 11, image = R.drawable.monster_1, stepNumber = 1, id = 1101),
            ProductEntity(productId = 11, image = R.drawable.monster_2, stepNumber = 2, id = 1102),
            ProductEntity(productId = 11, image = R.drawable.monster_3, stepNumber = 3, id = 1103),
            ProductEntity(productId = 11, image = R.drawable.monster_4, stepNumber = 4, id = 1104),
            ProductEntity(productId = 11, image = R.drawable.monster_5, stepNumber = 5, id = 1105),
            ProductEntity(productId = 11, image = R.drawable.monster_6, stepNumber = 6, id = 1106),
            ProductEntity(productId = 11, image = R.drawable.monster_7, stepNumber = 7, id = 1107),
            ProductEntity(productId = 11, image = R.drawable.monster_8, stepNumber = 8, id = 1108),
            ProductEntity(productId = 11, image = R.drawable.monster_9, stepNumber = 9, id = 1109),
            ProductEntity(productId = 11, image = R.drawable.monster_10, stepNumber = 10, id = 1110),
            ProductEntity(productId = 11, image = R.drawable.monster_11, stepNumber = 11, id = 1111),
            ProductEntity(productId = 11, image = R.drawable.monster_12, stepNumber = 12, id = 1112),
            ProductEntity(productId = 11, image = R.drawable.monster_13, stepNumber = 13, id = 1113),
            ProductEntity(productId = 11, image = R.drawable.monster_14, stepNumber = 14, id = 1114),
            ProductEntity(productId = 11, image = R.drawable.monster_15, stepNumber = 15, id = 1115),
            ProductEntity(productId = 11, image = R.drawable.monster_16, stepNumber = 16, id = 1116),
            ProductEntity(productId = 11, image = R.drawable.monster_17, stepNumber = 17, id = 1117),
            ProductEntity(productId = 11, image = R.drawable.monster_18, stepNumber = 18, id = 1118),
            ProductEntity(productId = 11, image = R.drawable.monster_19, stepNumber = 19, id = 1119),
            ProductEntity(productId = 11, image = R.drawable.monster_20, stepNumber = 20, id = 1120),
            ProductEntity(productId = 11, image = R.drawable.monster_21, stepNumber = 21, id = 1121),
            ProductEntity(productId = 11, image = R.drawable.monster_22, stepNumber = 22, id = 1122),
            ProductEntity(productId = 11, image = R.drawable.monster_23, stepNumber = 23, id = 1123),
            ProductEntity(productId = 11, image = R.drawable.monster_24, stepNumber = 24, id = 1124),
            ProductEntity(productId = 11, image = R.drawable.monster_25, stepNumber = 25, id = 1125),
            ProductEntity(productId = 11, image = R.drawable.monster_26, stepNumber = 26, id = 1126),
            ProductEntity(productId = 11, image = R.drawable.monster_27, stepNumber = 27, id = 1127),
            ProductEntity(productId = 11, image = R.drawable.monster_28, stepNumber = 28, id = 1128),
            ProductEntity(productId = 11, image = R.drawable.monster_29, stepNumber = 29, id = 1129),
            ProductEntity(productId = 11, image = R.drawable.monster_30, stepNumber = 30, id = 1130),
            ProductEntity(productId = 11, image = R.drawable.monster_40, stepNumber = 40, id = 1140),
            ProductEntity(productId = 11, image = R.drawable.monster_41, stepNumber = 41, id = 1141),
            ProductEntity(productId = 11, image = R.drawable.monster_42, stepNumber = 42, id = 1142),
            ProductEntity(productId = 11, image = R.drawable.monster_43, stepNumber = 43, id = 1143),
            ProductEntity(productId = 11, image = R.drawable.monster_44, stepNumber = 44, id = 1144),
            ProductEntity(productId = 11, image = R.drawable.monster_45, stepNumber = 45, id = 1145),
            ProductEntity(productId = 11, image = R.drawable.monster_46, stepNumber = 46, id = 1146),
            ProductEntity(productId = 11, image = R.drawable.monster_47, stepNumber = 47, id = 1147),
            ProductEntity(productId = 11, image = R.drawable.monster_48, stepNumber = 48, id = 1148),
            ProductEntity(productId = 11, image = R.drawable.monster_49, stepNumber = 49, id = 1149),
            ProductEntity(productId = 11, image = R.drawable.monster_50, stepNumber = 50, id = 1150),
            ProductEntity(productId = 11, image = R.drawable.monster_51, stepNumber = 51, id = 1151),
            ProductEntity(productId = 11, image = R.drawable.monster_52, stepNumber = 52, id = 1152),
            ProductEntity(productId = 11, image = R.drawable.monster_53, stepNumber = 23, id = 1153),
            ProductEntity(productId = 11, image = R.drawable.monster_54, stepNumber = 24, id = 1154),

            ProductEntity(productId = 12, image = R.drawable.horse_1, stepNumber = 1, id = 1201),
            ProductEntity(productId = 12, image = R.drawable.horse_2, stepNumber = 2, id = 1202),
            ProductEntity(productId = 12, image = R.drawable.horse_3, stepNumber = 3, id = 1203),
            ProductEntity(productId = 12, image = R.drawable.horse_4, stepNumber = 4, id = 1204),
            ProductEntity(productId = 12, image = R.drawable.horse_5, stepNumber = 5, id = 1205),
            ProductEntity(productId = 12, image = R.drawable.horse_6, stepNumber = 6, id = 1206),
            ProductEntity(productId = 12, image = R.drawable.horse_7, stepNumber = 7, id = 1207),
            ProductEntity(productId = 12, image = R.drawable.horse_8, stepNumber = 8, id = 1208),
            ProductEntity(productId = 12, image = R.drawable.horse_9, stepNumber = 9, id = 1209),
            ProductEntity(productId = 12, image = R.drawable.horse_10, stepNumber = 10, id = 1210),


            ProductEntity(productId = 13, image = R.drawable.flower_1, stepNumber = 1, id = 1301),
            ProductEntity(productId = 13, image = R.drawable.flower_2, stepNumber = 2, id = 1302),
            ProductEntity(productId = 13, image = R.drawable.flower_3, stepNumber = 3, id = 1303),
            ProductEntity(productId = 13, image = R.drawable.flower_4, stepNumber = 4, id = 1304),
            ProductEntity(productId = 13, image = R.drawable.flower_5, stepNumber = 5, id = 1305),
            ProductEntity(productId = 13, image = R.drawable.flower_6, stepNumber = 6, id = 1306),
            ProductEntity(productId = 13, image = R.drawable.flower_7, stepNumber = 7, id = 1307),
            ProductEntity(productId = 13, image = R.drawable.flower_8, stepNumber = 8, id = 1308),
            ProductEntity(productId = 13, image = R.drawable.flower_9, stepNumber = 9, id = 1309),
            ProductEntity(productId = 13, image = R.drawable.flower_10, stepNumber = 10, id = 1310),
            ProductEntity(productId = 13, image = R.drawable.flower_11, stepNumber = 11, id = 1311),
            ProductEntity(productId = 13, image = R.drawable.flower_12, stepNumber = 12, id = 1312),
            ProductEntity(productId = 13, image = R.drawable.flower_13, stepNumber = 13, id = 1313),
            ProductEntity(productId = 13, image = R.drawable.flower_14, stepNumber = 14, id = 1314),


        )
    }


    fun getProducts(productId: Int): LiveData<List<ProductEntity>> {
        return dao.getByProduct(productId)
    }

    fun loadFavorite(itemId: Int) {
        viewModelScope.launch {
            favorite.postValue(itemDao.isFavorite(itemId))
        }
    }

    fun toggleFavorite(itemId: Int) {
        viewModelScope.launch {
            val current = itemDao.isFavorite(itemId)
            itemDao.updateFavorite(itemId, !current)
            favorite.postValue(!current)
        }
    }

}